import { run, assert } from './browser-harness.mjs'

const events = page => page.evaluate(() => Array.from(window.dataLayer || []).filter(x => x[0] === 'event').map(x => ({ name:x[1], params:x[2] })))
await run(async (page, base, width, output, browser) => {
  await page.goto(base + '/')
  await page.locator('.hbtn-line').click()
  let log = await events(page)
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => x.name === 'photo_quote_click').length, 1)
  assert.equal(log.filter(x => /quote_prepared|conversion|generate_lead|booking_form_submit/.test(x.name)).length, 0)

  await page.goto(base + '/calculator.html')
  await page.locator('#size-input').fill('30')
  await page.locator('.calc-btn').click()
  assert(await page.locator('#result-box').evaluate(el => el.classList.contains('show')))
  const link = await page.locator('#estimate-booking-link').getAttribute('href')
  assert(link.endsWith('#booking-form'))
  await page.goto(base + link.replace('?', '?utm_source=isolated-regression&'))
  await page.waitForFunction(() => document.getElementById('booking-form-details').open)
  assert.equal(new URL(page.url()).searchParams.has('note'), false)
  assert.equal(new URL(page.url()).searchParams.get('utm_source'), 'isolated-regression')
  assert.equal(await page.locator('#bk-size').inputValue(), '30坪')
  await page.locator('#bk-name').fill('隔離驗證姓名')
  assert.equal(await page.locator('#bk-name').inputValue(), '隔離驗證姓名')
  await page.locator('#bk-phone').fill('0900000000')
  await page.locator('#bk-note').fill('<img src=x onerror=alert(1)> 隔離測試備註')
  await page.locator('.bk-submit').click()
  await page.locator('#bk-copy-btn').click()
  assert.match(await page.locator('#bk-next-note').innerText(), /無法自動複製/)
  assert.match(await page.locator('#bk-msg-text').innerText(), /隔離驗證姓名/)
  assert.equal(await page.locator('#bk-msg-text img').count(), 0)
  assert((await page.locator('.bk-line-btn').getAttribute('href')).includes('@117adltu'))
  await page.locator('.bk-line-btn').click()
  log = await events(page)
  assert.equal(log.filter(x => x.name === 'quote_prepared').length, 1)
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => /conversion|generate_lead|booking_form_submit/.test(x.name)).length, 0)
  assert(!JSON.stringify(log).includes('隔離'))
  assert(!JSON.stringify(log).includes('0900000000'))
  await page.getByText('重新填寫', { exact:true }).click()
  assert.equal(await page.locator('#bk-name').inputValue(), '隔離驗證姓名')
  await page.locator('.bk-submit').click()
  assert.equal((await events(page)).filter(x => x.name === 'quote_prepared').length, 1)
  await page.screenshot({ path:`${output}/${browser}-${width}-quote.png` })

  await page.goto(base + '/')
  await page.evaluate(() => showPage('cases'))
  await page.locator('.photo-compare').first().waitFor()
  const compare = page.locator('.photo-compare').first()
  await compare.focus()
  await page.keyboard.press('ArrowRight')
  assert.equal(await compare.getAttribute('role'), 'slider')
  await page.evaluate(() => showPage('services'))
  const service = page.locator('.svc-item').first()
  const wasExpanded = await service.getAttribute('aria-expanded')
  await service.focus(); await page.keyboard.press('Enter')
  assert.equal(await service.getAttribute('aria-expanded'), wasExpanded === 'true' ? 'false' : 'true')

  await page.goto(base + '/?isolated=blank#booking-form')
  await page.waitForFunction(() => document.getElementById('booking-form-details').open)
  // Capture synchronously before location.href leaves the document.
  log = await page.evaluate(() => {
    submitBookingForm({ preventDefault() {} })
    return Array.from(window.dataLayer || []).filter(x => x[0] === 'event').map(x => ({ name:x[1], params:x[2] }))
  })
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => /quote_prepared|conversion/.test(x.name)).length, 0)
}, ['/', '/calculator.html', '/taipei.html', '/new-taipei.html', '/taoyuan.html', '/keelung.html', '/yilan.html'], '_site')
