import { run, assert } from './browser-harness.mjs'

const events = page => page.evaluate(() => Array.from(window.dataLayer || []).filter(x => x[0] === 'event').map(x => ({ name:x[1], params:x[2] })))
await run(async (page, base, width, output, browser) => {
  await page.goto(base + '/')
  assert.equal(await page.locator('.hero-photo').getAttribute('src'), 'cases/case07-after.jpg')
  assert.equal(await page.locator('.field-before img').getAttribute('src'), 'cases/case07-before.jpg')
  assert.equal(await page.locator('.hero [src*="hero-photo"]').count(), 0)
  await page.evaluate(() => document.activeElement?.blur())
  await page.screenshot({ path:`${output}/${browser}-${width}-home-full.png`, fullPage:true })
  await page.locator('.field-photo a').focus()
  await page.keyboard.press('Enter')
  await page.locator('#page-cases.active').waitFor()
  assert.equal(new URL(page.url()).hash, '#cases')
  await page.locator('.photo-case-card').first().waitFor()
  assert.equal(await page.locator('.photo-case-card').count(), 11)
  const caseLinks = page.locator('.case-inquiry')
  assert.equal(await caseLinks.count(), 11)
  const subject = await page.locator('.photo-case-info h4').first().textContent()
  assert(decodeURIComponent(await caseLinks.first().getAttribute('href')).includes(subject))
  await caseLinks.first().focus(); await page.keyboard.press('Enter')
  const caseLog = await events(page)
  assert.equal(caseLog.filter(x => x.name === 'line_click').length, 1)
  assert.equal(caseLog.filter(x => x.name === 'photo_quote_click').length, 1)
  assert.equal(caseLog.find(x => x.name === 'line_click').params.cta_context, 'case_inquiry')
  assert.equal(caseLog.filter(x => /conversion|quote_prepared/.test(x.name)).length, 0)
  await page.reload()
  await page.locator('#page-cases.active').waitFor()
  await page.goBack()
  await page.locator('#page-home.active').waitFor()
  const serviceIds = ['service-home','service-renovation','service-deep','service-move','service-community','service-business','service-organizing']
  for (let i = 0; i < serviceIds.length; i++) {
    const entry = page.locator('.service-choice, .service-more button').nth(i)
    await entry.focus(); await page.keyboard.press('Enter')
    await page.locator(`#${serviceIds[i]}[aria-expanded="true"]`).waitFor()
    assert.equal(new URL(page.url()).hash, '#' + serviceIds[i])
    const inquiry = page.locator(`#${serviceIds[i]} .service-actions a[data-line-context="service_inquiry"]`)
    const serviceTitle = await page.locator(`#${serviceIds[i]} .svc-title`).textContent()
    assert(decodeURIComponent(await inquiry.getAttribute('href')).includes(serviceTitle))
    const before = (await events(page)).filter(x => x.name === 'line_click').length
    await inquiry.focus(); await page.keyboard.press('Enter')
    const serviceLog = await events(page)
    assert.equal(serviceLog.filter(x => x.name === 'line_click').length, before + 1)
    assert.equal(serviceLog.filter(x => x.name === 'line_click').at(-1).params.cta_context, 'service_inquiry')
    assert.equal(serviceLog.filter(x => /quote_prepared|conversion/.test(x.name)).length, 0)
    if (i === 1) {
      await inquiry.scrollIntoViewIfNeeded()
      await page.evaluate(() => document.activeElement?.blur())
      await page.screenshot({ path:`${output}/${browser}-${width}-service-inquiry.png` })
    }
    await page.goBack()
    await page.locator('#page-home.active').waitFor()
  }
  await page.goto(base + '/#service-renovation')
  await page.locator('#service-renovation[aria-expanded="true"]').waitFor()
  assert.equal(await page.locator('#service-renovation .svc-head').getAttribute('aria-expanded'),'true')
  await page.locator('#service-renovation .service-actions a[href="#booking-form"]').click()
  await page.locator('#page-home.active').waitFor()
  assert.equal(new URL(page.url()).hash, '#booking-form')
  assert.equal(await page.locator('#bk-service').inputValue(), await page.locator('#service-renovation .svc-title').textContent())
  assert(await page.locator('#booking-form').evaluate(el => el.getBoundingClientRect().top >= document.querySelector('.top-bar').getBoundingClientRect().bottom))
  await page.locator('#bk-service').selectOption('大掃除')
  await page.locator('#bk-note').fill('保留原需求')
  await page.evaluate(() => showService('service-community'))
  await page.locator('#service-community .service-actions a[href="#booking-form"]').click()
  assert.equal(await page.locator('#bk-service').inputValue(), '大掃除')
  assert.equal(await page.locator('#bk-note').inputValue(), '保留原需求')
  for (let attempt=0; attempt<5; attempt++) {
    await page.goto(base + '/#service-renovation')
    await page.locator('#service-renovation .service-actions a[href="#booking-form"]').click()
    await page.locator('#page-home.active').waitFor()
    assert.equal(new URL(page.url()).hash, '#booking-form')
  }
  await page.goto(base + '/#booking-form')
  assert.equal(await page.locator('.bk-form label').count(), 7)
  assert.equal(await page.locator('.bk-form label').filter({hasText:'選填'}).count(), 7)
  await page.locator('#bk-note').fill('只先詢問浴室水垢，其他資料稍後補充')
  await page.locator('.bk-submit').click()
  await page.locator('#bk-confirm').waitFor()
  assert((await page.locator('#bk-msg-text').textContent()).includes('只先詢問浴室水垢'))
  assert.equal(await page.locator('#bk-name').inputValue(), '')
  assert.equal(await page.locator('#bk-phone').inputValue(), '')
  await page.goto(base + '/')
  const nav = page.locator(width >= 840 ? '.desktop-nav' : '.bottom-nav')
  for (const route of ['pricing','services','cases']) {
    await nav.locator(`[data-page="${route}"]`).click()
    await page.locator(`#page-${route}.active`).waitFor()
    assert.equal(new URL(page.url()).hash, '#' + route)
    await page.evaluate(() => { document.activeElement?.blur(); scrollTo(0,0) })
    await page.screenshot({ path:`${output}/${browser}-${width}-${route}.png` })
  }
  await page.goto(base + '/#about')
  await page.locator('#page-about.active').waitFor()
  await page.evaluate(() => { document.activeElement?.blur(); scrollTo(0,0) })
  await page.screenshot({ path:`${output}/${browser}-${width}-about.png` })
  await page.goto(base + '/')
  const faq = page.locator('.mini-faq-item').first()
  await faq.locator('summary').click()
  await faq.locator('a').click()
  await page.locator('#page-pricing.active').waitFor()
  await page.goBack()
  await page.locator('#page-home.active').waitFor()
  const nojs = await page.context().browser().newContext({ javaScriptEnabled:false, viewport:{width,height:900} })
  await nojs.route('**/*', route => route.request().url().startsWith(base) ? route.continue() : route.abort())
  const plain = await nojs.newPage()
  await plain.goto(base + '/')
  await plain.locator('.field-photo a').click()
  assert.equal(new URL(plain.url()).hash, '#cases')
  assert(await plain.locator('#page-cases').isVisible())
  assert(await plain.locator('#page-services').isVisible())
  assert(await plain.locator('#service-renovation .svc-body').isVisible())
  assert(await plain.locator('#psec-reno').isVisible())
  assert.equal(await plain.locator('.nojs-note a[href^="https://line.me"]').count(),1)
  assert.equal(await plain.locator('.service-actions a[data-line-context="service_inquiry"]').count(), 7)
  assert.equal(await plain.locator('.service-actions a[data-booking-service]').first().isVisible(), false)
  await nojs.close()
  await page.locator('.hbtn-line').click()
  let log = await events(page)
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => x.name === 'photo_quote_click').length, 1)
  assert.equal(log.filter(x => /quote_prepared|conversion|generate_lead|booking_form_submit/.test(x.name)).length, 0)

  await page.goto(base + '/calculator.html')
  await page.locator('#size-input').fill('30')
  await page.locator('.calc-btn').click()
  assert(await page.locator('#result-box').evaluate(el => el.classList.contains('show')))
  const link = await page.locator('#estimate-booking-link').getAttribute('href')
  assert(link.endsWith('#booking-form'))
  await page.goto(base + link.replace('?', '?utm_source=isolated-regression&'))
  await page.waitForFunction(() => document.getElementById('booking-form-details').open)
  assert.equal(new URL(page.url()).searchParams.has('note'), false)
  assert.equal(new URL(page.url()).searchParams.get('utm_source'), 'isolated-regression')
  assert.equal(await page.locator('#bk-size').inputValue(), '30坪')
  await page.locator('#bk-name').fill('隔離驗證姓名')
  assert.equal(await page.locator('#bk-name').inputValue(), '隔離驗證姓名')
  await page.locator('#bk-phone').fill('0900000000')
  await page.locator('#bk-note').fill('<img src=x onerror=alert(1)> 隔離測試備註')
  await page.locator('.bk-submit').click()
  await page.locator('#bk-copy-btn').click()
  assert.match(await page.locator('#bk-next-note').innerText(), /無法自動複製/)
  assert.match(await page.locator('#bk-msg-text').innerText(), /隔離驗證姓名/)
  assert.equal(await page.locator('#bk-msg-text img').count(), 0)
  assert((await page.locator('.bk-line-btn').getAttribute('href')).includes('@117adltu'))
  assert.equal(await page.locator('.bk-line-btn').getAttribute('href'), 'https://line.me/R/ti/p/@117adltu')
  assert.match(await page.evaluate(() => decodeURIComponent(bookingLineUrl())), /隔離驗證姓名/)
  assert(!(await page.locator('a[href]').evaluateAll(links => links.map(a => a.href).join('\n'))).includes('0900000000'))
  await page.locator('.bk-line-btn').click()
  log = await events(page)
  assert.equal(log.filter(x => x.name === 'quote_prepared').length, 1)
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => /conversion|generate_lead|booking_form_submit/.test(x.name)).length, 0)
  assert(!JSON.stringify(log).includes('隔離'))
  assert(!JSON.stringify(log).includes('0900000000'))
  await page.getByText('重新填寫', { exact:true }).click()
  assert.equal(await page.locator('#bk-name').inputValue(), '隔離驗證姓名')
  await page.locator('.bk-submit').click()
  assert.equal((await events(page)).filter(x => x.name === 'quote_prepared').length, 1)
  await page.screenshot({ path:`${output}/${browser}-${width}-quote.png` })

  await page.goto(base + '/')
  await page.evaluate(() => showPage('cases'))
  await page.locator('.photo-compare').first().waitFor()
  const compare = page.locator('.photo-compare').first()
  await compare.focus()
  await page.keyboard.press('ArrowRight')
  assert.equal(await compare.getAttribute('role'), 'slider')
  await page.evaluate(() => showPage('services'))
  const service = page.locator('.svc-item').first()
  const wasExpanded = await service.getAttribute('aria-expanded')
  await service.locator('.svc-head').focus(); await page.keyboard.press('Enter')
  assert.equal(await service.getAttribute('aria-expanded'), wasExpanded === 'true' ? 'false' : 'true')

  await page.goto(base + '/?isolated=blank#booking-form')
  await page.waitForFunction(() => document.getElementById('booking-form-details').open)
  // Capture synchronously before location.href leaves the document.
  log = await page.evaluate(() => {
    submitBookingForm({ preventDefault() {} })
    return Array.from(window.dataLayer || []).filter(x => x[0] === 'event').map(x => ({ name:x[1], params:x[2] }))
  })
  assert.equal(log.filter(x => x.name === 'line_click').length, 1)
  assert.equal(log.filter(x => /quote_prepared|conversion/.test(x.name)).length, 0)
}, ['/', '/calculator.html', '/taipei.html', '/new-taipei.html', '/taoyuan.html', '/keelung.html', '/yilan.html', '/privacy.html', '/terms.html'], '_site')
